// front/SaviraWood/src/routes/pictures/[id]/+page.svelte
<div class="flex flex-row">
    <div>
        <img src={prodPic} alt="prodPic">
    </div>
    <div>
        <h1 class="text-4xl">{data.prod.name}</h1>
        <p>£{data.prod.price}</p>
        <p>Details: <br> Width: {data.prod.width} <br> Height: {data.prod.height} <br> Weight: {data.prod.weight}</p>
    </div>
</div>

<script>
    export let data;
    import prodPic from '$lib/pics/Clocks_(Time_to_Live)/Clocks_TTL_all.jpg'
</script>

// front/SaviraWood/pages/pictures/[id].vue
<template>
    <div>
        <h1>Name: {{ pictures.name }}</h1>
        <p>price: {{ pictures.price }}</p>
        <p>photo: <nuxt-img :src="`/pics/Big_Ship/${prodName}`" alt="prod_pic" class="w-36" /></p>
    </div>
</template>

<script setup>
    const { id } = useRoute().params
    const { data: pictures } = await useFetch(`http://127.0.0.1:5000/pictures/${id}`)
    const prodName = "Big_Ship_View.jpg"
</script>

<style scoped>

</style>
